### ISSUE TITLE
An error has occurred: java.lang.NullPointerException

### ISSUE THREAD

**Issue by evandrocoan** [plantuml/plantuml#105]
![projectclassdiagram](https://user-images.githubusercontent.com/5332158/37236543-79edaa1c-23e7-11e8-9354-2f4b1f2cd74b.png)

```
dot -version
dot - graphviz version 2.38.0 (20140413.2041)
libdir = "D:\User\Documents\graphviz-2.38\release\bin"
Activated plugin library: gvplugin_dot_layout.dll
Using layout: dot:dot_layout
Activated plugin library: gvplugin_core.dll
Using render: dot:core
Using device: dot:dot:core
The plugin configuration file:
        D:\User\Documents\graphviz-2.38\release\bin\config6
                was successfully loaded.
    render      :  cairo dot fig gd gdiplus map pic pov ps svg tk vml vrml xdot
    layout      :  circo dot fdp neato nop nop1 nop2 osage patchwork sfdp twopi
    textlayout  :  textlayout
    device      :  bmp canon cmap cmapx cmapx_np dot emf emfplus eps fig gd gd2 gif gv imap imap_np ismap jpe jpeg jpg metafile pdf pic plain plain-ext png pov ps ps2 svg svgz tif tiff tk vml vmlz vrml wbmp xdot xdot1.2 xdot1.4
    loadimage   :  (lib) bmp eps gd gd2 gif jpe jpeg jpg png ps svg
```

<details>
<p>

```

@startuml
  skinparam defaultFontName Consolas

  MainWindow      <|-- Gtk::Window
  MainWindow      *--  Viewport : viewport

  DrawOptionsBox  <|-- Gtk::Frame     ' remove this to fix the error
  DrawOptionsBox  *-- MainWindow      : mainWindow
  DrawOptionsBox  *-- AddObjectWindow : add_object_window

  class MainWindow {
    Gtk::Box   main_box
    Gtk::Box   left_box
    Gtk::Frame left_frame
    Gtk::Frame right_frame
    Viewport*  getViewport()
  }

  AddObjectWindow <|-- Gtk::Window
  AddObjectWindow *-- DrawOptionsBox  : draw_options_box

  Viewport <|-- Gtk::DrawingArea
  Viewport *-- Viewwindow
  Viewport *-- DisplayFile

  class AddObjectWindow {
    Gtk::Grid              point_grid
    Gtk::Grid              line_grid
    Gtk::Grid              polygn_grid
    std::list<Coordinate*> polygon_cord_list
  }

  class DisplayFile {
    std::map< string, DrawableObject* > objectsMap
    void addObject( DrawableObject* )
    void removeObject( DrawableObject* )
    void removeObjectByName( string )
  }

@enduml
```
</p>
</details><br>

If you remove the `' remove this to fix the error` it compiles correctly.

**Comment by arnaudroques** [comment]
Thanks for the report.
This has been fixed in last beta http://beta.plantuml.net/plantuml.jar
Since you are using the .war you can overwrite the existing .jar in your war file with the new plantuml.jar

Regards,

**Comment by evandrocoan** [comment]
I am just running a local server with https://github.com/plantuml/plantuml-server

I could not any `.war` or `.jar` file on the server folder:

![image](https://user-images.githubusercontent.com/5332158/37493316-4c13bdfc-2883-11e8-9ceb-0eeb869fe2a7.png)


How can I update it?

**Comment by arnaudroques** [comment]
Ok, we've put a patched war file on http://beta.plantuml.net/plantuml.war
Tell us if it's working for you!

**Comment by evandrocoan** [comment]
I still do not know what to do with a `.war` file. I just run `mvn jetty:run` and the `plantuml-server` just setup everything by himself and start working.

I killed my server and started it again, then I monitored the files it loaded, and I found the `plantuml-server` is reading the file from my user directory at:
```
C:\Users\User\.m2\repository\net\sourceforge\plantuml\plantuml\1.2018.1\plantuml-1.2018.1.jar
```
Then I replaced that `.jar` with the beta one you gave me and it is working now, no crashes:
<details>
<p>

![projectclassdiagram](https://user-images.githubusercontent.com/5332158/37494296-fa1a32c0-2886-11e8-8982-d277f2bf9333.png)
</p>
</details><br>
