### ISSUE TITLE
"Drunken Font" 

### ISSUE THREAD

**Issue by snooppr** [plantuml/plantuml#1202]
Just now I noticed that the distances between the letters are non-metric, but rather chaotic.  It's not beautiful.  Here is a sample code:
```
@startmindmap
scale 1480*740
title Создано в Termux ©https://habr.com/ru/users/ne555/
*[#lightgreen] **Termux**
** <&audio-spectrum>Мультимедиа
***_ mp3splt
***_ cmus
***_ cava
***_ ffmpeg
***_ imagemagick
***_ chafa
***_ <s>youtubedr</s> => yt-dlp
** <&data-transfer-download>Парсинг данных
***_ curl..wget
***_ примеры
** <&cloud-upload>Автобэкап данных
***_ rclone
***_ 7-zip
***_ cronie
** <&bar-chart>Data Science
***_ numpy
***_ scipy
***_ pandas
***_ matplotlib
***_ jupyter
***_ wordcloud
***_ visidata
** <&envelope-closed>Работа с письмами
***_ mutt
** <&magnifying-glass>OSINT
***_ check_email(s)
***_ check_account(s)
left side
** <&terminal>Программирование на Android
***_ python..brainfuck
** <&layers>Сравнение пакетов
***_ html2text*
***_ links
** <&lock-unlocked>Пентест
***_ сниффинг
***_ скан
***_ брутфорс
***_ дамп
***_ фишинг
** <&shield>Системное администрирование
***_ chattr..nethogs
** <&document>Пользовательское ПО
***_ yaspeller
***_ povray
***_ gnuplot
***_ plantuml
***_ steghide
***_ gpg
***_ tor
** <&wrench>Установка и настройка среды
***_ widget..proot-distro
@endmindmap
```
![test](https://user-images.githubusercontent.com/61022210/204868584-39b33f34-cc40-4682-b229-60847be80a2c.jpg)

Pay attention to the dancing characters, "rl" in curl stuck together, and "vis idata" became like a space.  I've tried plantuml on Termux and on GNU/Linux with disappointing results.

**Comment by arnaudroques** [comment]
Which version of PlantUML are you using?
It is possible that it has been fixed in last releases.
Online versions of [png](http://www.plantuml.com/plantuml/png/RLJDZXj54BxxAKP2GZ3IZ0Da5OIMKP2uS853SaCeQi-qPnhtTBUwgtTZJkjDa90sI3m00Y9EtBoEhPY5jIMUeFkDg9dgZH3AOJprrTJFzrLr-w43Pg4NgkcPcRYQIPvzSF_ZU_c3-_Sc801XU1aEuNNOXdMu3OSiRBB7tFR-QVRF7ns0SPzCfnsRsRBM_TJwgNVSkgdY9oSdqqd-zJjIj1sqbdFrJPRdb9hdappFJjzblX6wS8RNO7rVXP_Zi_1NV14lmpxy7NPXY-yrXkPFijvyv8m40dNlNRBO6IDhFkyDRyaMFMivFg9UfB2EpLFSgQkMseEVySQUJbsLVLfbIoWQQOXJmu0LO9boSswBHfyhgLbJXL_3Ebx45JAw3Q-oD8xRU1M_JosybMLvtd8W78xnWcHWsXNLhgNsJU4DLVmfR53f8Lp77yCDbZk-fQh55CN9Vb1y9qngPhKId8hEc2rGduNgSwIUFQe5LtLAKRutIp9TBUvCmrJ3N9eh0wG3Kim8V-lD4hWbSAvjCt8cU2QS6CP3VRawur8RNc24uwZdDoH_7GweQPt55GuWxECgli0HhF7PftuUWF9nFqhCbqArHIkPSzLNZxxuyl7TldYzU88h5F8zz_v_VQokjLSmU2MVGuQCqXoGTIyKaxWgdFmXlCBVeJ6s7l5cdEq-x39yhRFFL6ErICfGSwTLMSui4shkwmMLb6p9hQl2ox7K1lDsToMEwBW9kt616ohIGIy_1FuKSi9Ig8LBXNIzABmQNdmyIrW7KtSudqiAZgkXSdmUdzC9U-Ez6MWJ2jTub9x5IumveBLAtkqeyqXeo8y_K0tgxJh1POCYndLWKmp6YumYC6-B06Ff4whytwZUt1u0MvQAuvJQ9AdHjU-vWa7DORYruJLbZYqGZzo7DXZm2nLQCcUubDmIDFhCiYNPhHgk1QGFaYdmlIJaWBSThZa5cfOCq9QOd5kkwguAlu_oaFd80-UMXVsuQzA6tZz7By8BfBYDL-cKYwRbK9R6QWr58nnOFNd8LPF-5ly5) or [svg](http://www.plantuml.com/plantuml/svg/RLJDZXj54BxxAKP2GZ3IZ0Da5OIMKP2uS853SaCeQi-qPnhtTBUwgtTZJkjDa90sI3m00Y9EtBoEhPY5jIMUeFkDg9dgZH3AOJprrTJFzrLr-w43Pg4NgkcPcRYQIPvzSF_ZU_c3-_Sc801XU1aEuNNOXdMu3OSiRBB7tFR-QVRF7ns0SPzCfnsRsRBM_TJwgNVSkgdY9oSdqqd-zJjIj1sqbdFrJPRdb9hdappFJjzblX6wS8RNO7rVXP_Zi_1NV14lmpxy7NPXY-yrXkPFijvyv8m40dNlNRBO6IDhFkyDRyaMFMivFg9UfB2EpLFSgQkMseEVySQUJbsLVLfbIoWQQOXJmu0LO9boSswBHfyhgLbJXL_3Ebx45JAw3Q-oD8xRU1M_JosybMLvtd8W78xnWcHWsXNLhgNsJU4DLVmfR53f8Lp77yCDbZk-fQh55CN9Vb1y9qngPhKId8hEc2rGduNgSwIUFQe5LtLAKRutIp9TBUvCmrJ3N9eh0wG3Kim8V-lD4hWbSAvjCt8cU2QS6CP3VRawur8RNc24uwZdDoH_7GweQPt55GuWxECgli0HhF7PftuUWF9nFqhCbqArHIkPSzLNZxxuyl7TldYzU88h5F8zz_v_VQokjLSmU2MVGuQCqXoGTIyKaxWgdFmXlCBVeJ6s7l5cdEq-x39yhRFFL6ErICfGSwTLMSui4shkwmMLb6p9hQl2ox7K1lDsToMEwBW9kt616ohIGIy_1FuKSi9Ig8LBXNIzABmQNdmyIrW7KtSudqiAZgkXSdmUdzC9U-Ez6MWJ2jTub9x5IumveBLAtkqeyqXeo8y_K0tgxJh1POCYndLWKmp6YumYC6-B06Ff4whytwZUt1u0MvQAuvJQ9AdHjU-vWa7DORYruJLbZYqGZzo7DXZm2nLQCcUubDmIDFhCiYNPhHgk1QGFaYdmlIJaWBSThZa5cfOCq9QOd5kkwguAlu_oaFd80-UMXVsuQzA6tZz7By8BfBYDL-cKYwRbK9R6QWr58nnOFNd8LPF-5ly5) results look fine.

**Comment by snooppr** [comment]
On GNU/Linux, this is the latest version in the debian repo: 1.2020.2+ds-1. 
In Termux it is v1.2021.16

**Comment by arnaudroques** [comment]
Both versions are quite old (any idea on how to update the debian repo?)

Is it possible for you to upgrade?
(Note that you will to use [skin rose](http://www.plantuml.com/plantuml/uml/RLJ1ZXj54BtxAqP2GZ3IZ0Da5OIMKP2uS853SaCeQi-KPnhtT8-wgtTZJkjDa90sI7m08aISk7atQyKin2ln1Tr_HCrK9qA8WptrobMlwhtfzds7mc8lTTEBOUPMKcVME9YvMYZ8FhZxyPtytjqxCvH8CBm8X_0gN8TjU1qEMRZA7eBj_UFixzyxnC5zCfztOc7BslHpw-VUWNLp3KT7H_DP_lKxIhOTjXP0VvFbERVc-IpFi-DtXM-aATm0DLhVL-7d-2Jy6P_5yx0FVuLTkARdbahpHra_VEG6XGpgthiKYHF1qNBP3z1oB7lH0dralKfbdLYckcDNhOr7lu367izTbNrQPMii6ZNmJer0KQ0LsYt15eqvrSg8fWhFmpQUnKtOamilisJ7wtWHlqyZl5LbUTe2CWwtyOnbKDi5SzVA-ARm0pF-5Av8wI5SnX_33T7T_W-hfHOD7DyhlfD36cQDbi2a2s4BqcUn-boWo1xK4dITMhJlXpM7hfPlma7eHhZagq1Q1vLSCFxM3si4o-3Ks6RQcU69T7AqX-U2FW5b1YYemW7f-PMMlmm7qhJDueOC2FkuYS_8WYrzzccUH-J-NhHQBjTIjqMhX7FLLm---F9XqjT1lNe4lP3gFVV-ltEYhetNE6OLB36ZZP8F2BQNMYXwLUJy8Roaxt4mZPxmrUJjFkmoUcopptHZZKpAI7DdT5akh91wwUiLKogn1kkgy6AYkgA-tHkAMqhSX1s99MOcwR1N7o8ynfonadhb4f6fLuNNumEciqGyrBeZVywvE6v6vlWqFkKJzZPxCwxDA5pIKNeIpwdcGD4cPQydcRUCnlxu0tFmRDT9K0s9c5u73QLYkiWaWlgk2L0j_qGg_sFLszk3QCjI0xdK9acDgNqF6aSrX_7MXbVSEOqWFExEOvw7NvXeBTm0Ie5DhfiJAzOSjtgy5fX-K4AZxnKZXz1sie5KEBGSeB6yoQa5NNTL-6sIHvjFUv1lMTXFxvgrKVQFAKlmRFnpYHVfbCkc1IpBmHg3HICTMZEx3xf9Vv3_0000) in your diagram if you want to keep the legacy look&feel)

**Comment by snooppr** [comment]
I updated Plantuml on Termux to the latest version v1.2022.13 And the problem still persists.

As far as Debian is concerned, the version even in the test branch with the latest packages is "outdated": v1:1.2020.2+ds-1

The Deb package page lists the emails of the Plantuml maintainers, you can email them:
Andrew Shadura andrewsh@debian.org
Christopher Hoskin mans0954@debian.org

**Comment by arnaudroques** [comment]
Ok, thanks.
The good news is that we were able to reproduce the issue on some config :-)
This turns out to be [a ligature issue](https://en.wikipedia.org/wiki/Ligature_(writing)).

The font you are using enables some ligatures that, for example, are used for some characters (typical example being "fi")
So here is the minimum example [that shows the issue](http://www.plantuml.com/plantuml/uml/SoWkIImgoStCIybDBE0gJaxCILKmuz9IICi4GIw7LA04H180).

Could you list on your system all fonts using http://www.plantuml.com/plantuml/uml/oyaiBadBpojHICi4GG00 ? And then check if some fonts do not use ligature.

If anyone knows how to control those ligatures behaviours from the java code, please post here because we have found very little information about it...

Thanks!

**Comment by snooppr** [comment]
1. https://github.com/plantuml/plantuml/issues/1202#issuecomment-1333476276
Please note that in your examples in this comment, **.svg** displays the location of the characters correctly, and the **.png** format is worse compared to the screenshot
<details>
<summary>spoiler: svg vs png comparison</summary>

![Без имени](https://user-images.githubusercontent.com/61022210/205244653-c637044a-1fe7-43ce-8e09-8afce5b94170.png)
Left png and right svg
</details>

--------------------------------

2. >Could you list on your system all fonts
<details>
<summary>spoiler: Fonts on GNU/Linux & Termux in plantuml</summary>

### GNU/Linux deb
![android](https://user-images.githubusercontent.com/61022210/205245435-5adbe534-968b-4db0-aa6a-8d84b8bc4210.png)


### Android Termux
![plan](https://user-images.githubusercontent.com/61022210/205245445-1f5a34c6-6bef-4b5c-bc2b-4b0d2e99a09e.png)

</details>

In Linux, the locale is utf-8, and in Termux, C.utf-8

On Linux, the default fonts are: "Sans Reqular" and "Monospace Reqular" (changing to other fonts in the OS itself, for example "Arial" did not change anything when working with Plantuml).

I usually encounter "dancing text" on Android and Linux with other applications and libraries when displaying svg format. Plantuml has something similar, but not so pronounced and surprisingly in png format.

**Comment by snooppr** [comment]
I checked the fonts in the OS on my Android cyrillic and latin.
```
@startuml
listfont Latin Кириллица
@enduml
```
`$ plantuml file`

I checked ten fonts supported by both encodings (Lat/Kir)
The text got really better, but not perfect, but something like in this example:https://github.com/plantuml/plantuml/issues/1202#issuecomment-1333476276

Workarounds I found:
1. Create a flowchart in **svg** format: 
`$ plantuml -tsvg file` and subsequent conversion to png format

2. If you add to the flowchart code:

```
@startmindmap
skinparam defaultFontSize 24
...code...
@endmindmap
```
`$ plantuml file`
**png** renders well _(and the text on the flowchart is not enlarged)_.
