### ISSUE TITLE
Skinparam inconsistencies on class diagram grouping elements

### ISSUE THREAD

**Issue by DRKV333** [plantuml/plantuml#1464]
**Describe the bug**
There are various problems with `skinparam`s on the nestable elements found in class/deployment diagrams.
 
```
@startuml

title %version()

allowmixing

skinparam packageFontColor green
skinparam packageBorderColor red
skinparam packageStereotypeFontColor blue

package EmptyPackage <<something>>

package PackageWithThing <<something>> {
    class a
}

rectangle EmptyRectangle <<something>>

rectangle RectangleWithThing <<something>> {
    class b
}

@enduml
```
![image](https://github.com/plantuml/plantuml/assets/30904009/537d287a-9e31-4e60-9bdd-7835658e334e)

* *FontColor and *StereotypeFontColor don't work at all. They do work on the empty package elements from deployment diagrams though.
* *BorderColor works, but it isn't listed in `skinparameters`.
* For nesting elements PackageBorderColor applies to other kinds of groups (`rectangle`, `node`, etc.) as well. However, it doesn't apply to empty versions of theses elements.

**Expected behavior**
* *FontColor and *StereotypeFontColor should work for nesting elements.
* *BorderColor should be listed in `skinparameters`.
* `skinparam` behavior should be consistent between nesting and empty elements of the same type.

**Desktop (please complete the following information):**

- OS: Windows
- Version 1.2023.9beta4

**Comment by The-Lum** [comment]
Hi @DRKV333,

Thanks a lot for all your examples, _in order to help PlantUML team to debug..._

Regards.

**Comment by arnaudroques** [comment]
Many thanks for your tests, it really helps.
The situation is complex :-)

We have fixed some issues [in last snapshot](https://github.com/plantuml/plantuml/releases/tag/snapshot) (see [this example](http://www.plantuml.com/plantuml/uml/NO_DIiKm48NtynJp08BSdsK85qHNBaG4rxczGngS92MPeaNwxaQRqE3odFaE7tF9OfBCda6SC66MXGd0CCTFxxvSi03ghzGmcU73MBh3H8EOO0l-3OXFCSX3v9ZG9g9GccSNQ6iItKhEGecYBDCsw2TNdgbKAwoWxgi7cWaV_IJBonOEg5IEdcHqmHwqtgaAl3iPttwFnvuyQbsb0vkSqHGJj0UguRN5KxyyQTsJ3Tezvvu-__DSY-T2uJPx_W40))

Unfortunately, we won't fix issues in skinparam. Skinparam are still supported for very simple case (and for ascending compatibility) but we would like people to migrate to style instead. (The main reason is that code for skinparam is too old and not very well written).

There are also some issues in style (like the one you have found) but we do want to fix them.

Tell us if you have some issues in migrating towards style as we may help you to do so!

**Comment by DRKV333** [comment]
I've ran through all the previously mentioned cases in 1.2023.10beta1, here are the things that work now:
* *FontColor and *StereotypeFontColor skinparams now work on nesting elements.
* For `<style>`: `package` `title` `FontColor` and `package` `stereotype` `fontColor` now work.

Things that still don't work;
* `title` `FontColor` applies to stereotypes on empty elements, but not on nesting elements.
* `composite` `LineColor` doesn't work

Skinparam related things that don't work:
* *BorderColor isn't listed in `skinparameters`.
* PackageBorderColor applies to all nesting elements.

I don't really mind if these two are not fixed.

Additionally, there seems to have been a regression, where `composite` `title` `FontColor` no longer applies to `package` specifically. (It still works with other nesting elements.)

`composite` doesn't seem to work with most things in general.
* `composite` `stereotype` `FontColor` doesn't work.
* `composite` `BackgroundColor` doesn't work.
* `composite` `LineColor` doesn't work.
* `composite` `FontSize` doesn't apply to `package`.
* `composite` `FontSize` doesn't apply to stereotypes. (But `element` `FontSize` does.)
* `composite` `stereotype` `FontSize` doesn't work.

Right now I'm just using skinparam because it's what I know, but really I'm fine with using whichever works better. Also skinparam has more documentation. I didn't find much on style, though I'm sure that will improve over time. If you can point me at the bits of code that make style work, I could also look at writing some docs myself.
